/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSkillsRouteImport } from './routes/_authenticated/skills'
import { Route as AuthenticatedSimulationRouteImport } from './routes/_authenticated/simulation'
import { Route as AuthenticatedSetupRouteImport } from './routes/_authenticated/setup'
import { Route as AuthenticatedProfilesRouteImport } from './routes/_authenticated/profiles'
import { Route as AuthenticatedPitchSetupRouteImport } from './routes/_authenticated/pitch-setup'
import { Route as AuthenticatedPersonasRouteImport } from './routes/_authenticated/personas'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedIntakeRouteImport } from './routes/_authenticated/intake'
import { Route as AuthenticatedFormationManagerRouteImport } from './routes/_authenticated/formation-manager'
import { Route as AuthenticatedFormationCandidatRouteImport } from './routes/_authenticated/formation-candidat'
import { Route as AuthenticatedFormationB2bReportRouteImport } from './routes/_authenticated/formation-b2b-report'
import { Route as AuthenticatedFormationB2bProjectionRouteImport } from './routes/_authenticated/formation-b2b-projection'
import { Route as AuthenticatedFormationB2bIndexRouteImport } from './routes/_authenticated/formation-b2b/index'
import { Route as AuthenticatedReportIdRouteImport } from './routes/_authenticated/report.$id'
import { Route as AuthenticatedPlayIdRouteImport } from './routes/_authenticated/play.$id'
import { Route as AuthenticatedFormationNegociationSimulationRouteImport } from './routes/_authenticated/formation-negociation/simulation'
import { Route as AuthenticatedFormationNegociationSetupRouteImport } from './routes/_authenticated/formation-negociation/setup'
import { Route as AuthenticatedFormationNegociationReportRouteImport } from './routes/_authenticated/formation-negociation/report'
import { Route as AuthenticatedFormationNegociationPersonasRouteImport } from './routes/_authenticated/formation-negociation/personas'
import { Route as AuthenticatedFormationB2bSimulationRouteImport } from './routes/_authenticated/formation-b2b/simulation'
import { Route as AuthenticatedFormationB2bSetupRouteImport } from './routes/_authenticated/formation-b2b/setup'
import { Route as AuthenticatedFormationB2bLaboPrixRouteImport } from './routes/_authenticated/formation-b2b/labo-prix'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSkillsRoute = AuthenticatedSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSimulationRoute = AuthenticatedSimulationRouteImport.update({
  id: '/simulation',
  path: '/simulation',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSetupRoute = AuthenticatedSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfilesRoute = AuthenticatedProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPitchSetupRoute = AuthenticatedPitchSetupRouteImport.update({
  id: '/pitch-setup',
  path: '/pitch-setup',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPersonasRoute = AuthenticatedPersonasRouteImport.update({
  id: '/personas',
  path: '/personas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIntakeRoute = AuthenticatedIntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFormationManagerRoute =
  AuthenticatedFormationManagerRouteImport.update({
    id: '/formation-manager',
    path: '/formation-manager',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFormationCandidatRoute =
  AuthenticatedFormationCandidatRouteImport.update({
    id: '/formation-candidat',
    path: '/formation-candidat',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFormationB2bReportRoute =
  AuthenticatedFormationB2bReportRouteImport.update({
    id: '/formation-b2b-report',
    path: '/formation-b2b-report',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFormationB2bProjectionRoute =
  AuthenticatedFormationB2bProjectionRouteImport.update({
    id: '/formation-b2b-projection',
    path: '/formation-b2b-projection',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFormationB2bIndexRoute =
  AuthenticatedFormationB2bIndexRouteImport.update({
    id: '/formation-b2b/',
    path: '/formation-b2b/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportIdRoute = AuthenticatedReportIdRouteImport.update({
  id: '/report/$id',
  path: '/report/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlayIdRoute = AuthenticatedPlayIdRouteImport.update({
  id: '/play/$id',
  path: '/play/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFormationNegociationSimulationRoute =
  AuthenticatedFormationNegociationSimulationRouteImport.update({
    id: '/formation-negociation/simulation',
    path: '/formation-negociation/simulation',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFormationNegociationSetupRoute =
  AuthenticatedFormationNegociationSetupRouteImport.update({
    id: '/formation-negociation/setup',
    path: '/formation-negociation/setup',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFormationNegociationReportRoute =
  AuthenticatedFormationNegociationReportRouteImport.update({
    id: '/formation-negociation/report',
    path: '/formation-negociation/report',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFormationNegociationPersonasRoute =
  AuthenticatedFormationNegociationPersonasRouteImport.update({
    id: '/formation-negociation/personas',
    path: '/formation-negociation/personas',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFormationB2bSimulationRoute =
  AuthenticatedFormationB2bSimulationRouteImport.update({
    id: '/formation-b2b/simulation',
    path: '/formation-b2b/simulation',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFormationB2bSetupRoute =
  AuthenticatedFormationB2bSetupRouteImport.update({
    id: '/formation-b2b/setup',
    path: '/formation-b2b/setup',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFormationB2bLaboPrixRoute =
  AuthenticatedFormationB2bLaboPrixRouteImport.update({
    id: '/formation-b2b/labo-prix',
    path: '/formation-b2b/labo-prix',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/formation-b2b-projection': typeof AuthenticatedFormationB2bProjectionRoute
  '/formation-b2b-report': typeof AuthenticatedFormationB2bReportRoute
  '/formation-candidat': typeof AuthenticatedFormationCandidatRoute
  '/formation-manager': typeof AuthenticatedFormationManagerRoute
  '/intake': typeof AuthenticatedIntakeRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/personas': typeof AuthenticatedPersonasRoute
  '/pitch-setup': typeof AuthenticatedPitchSetupRoute
  '/profiles': typeof AuthenticatedProfilesRoute
  '/setup': typeof AuthenticatedSetupRoute
  '/simulation': typeof AuthenticatedSimulationRoute
  '/skills': typeof AuthenticatedSkillsRoute
  '/formation-b2b/labo-prix': typeof AuthenticatedFormationB2bLaboPrixRoute
  '/formation-b2b/setup': typeof AuthenticatedFormationB2bSetupRoute
  '/formation-b2b/simulation': typeof AuthenticatedFormationB2bSimulationRoute
  '/formation-negociation/personas': typeof AuthenticatedFormationNegociationPersonasRoute
  '/formation-negociation/report': typeof AuthenticatedFormationNegociationReportRoute
  '/formation-negociation/setup': typeof AuthenticatedFormationNegociationSetupRoute
  '/formation-negociation/simulation': typeof AuthenticatedFormationNegociationSimulationRoute
  '/play/$id': typeof AuthenticatedPlayIdRoute
  '/report/$id': typeof AuthenticatedReportIdRoute
  '/formation-b2b/': typeof AuthenticatedFormationB2bIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/formation-b2b-projection': typeof AuthenticatedFormationB2bProjectionRoute
  '/formation-b2b-report': typeof AuthenticatedFormationB2bReportRoute
  '/formation-candidat': typeof AuthenticatedFormationCandidatRoute
  '/formation-manager': typeof AuthenticatedFormationManagerRoute
  '/intake': typeof AuthenticatedIntakeRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/personas': typeof AuthenticatedPersonasRoute
  '/pitch-setup': typeof AuthenticatedPitchSetupRoute
  '/profiles': typeof AuthenticatedProfilesRoute
  '/setup': typeof AuthenticatedSetupRoute
  '/simulation': typeof AuthenticatedSimulationRoute
  '/skills': typeof AuthenticatedSkillsRoute
  '/formation-b2b/labo-prix': typeof AuthenticatedFormationB2bLaboPrixRoute
  '/formation-b2b/setup': typeof AuthenticatedFormationB2bSetupRoute
  '/formation-b2b/simulation': typeof AuthenticatedFormationB2bSimulationRoute
  '/formation-negociation/personas': typeof AuthenticatedFormationNegociationPersonasRoute
  '/formation-negociation/report': typeof AuthenticatedFormationNegociationReportRoute
  '/formation-negociation/setup': typeof AuthenticatedFormationNegociationSetupRoute
  '/formation-negociation/simulation': typeof AuthenticatedFormationNegociationSimulationRoute
  '/play/$id': typeof AuthenticatedPlayIdRoute
  '/report/$id': typeof AuthenticatedReportIdRoute
  '/formation-b2b': typeof AuthenticatedFormationB2bIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/formation-b2b-projection': typeof AuthenticatedFormationB2bProjectionRoute
  '/_authenticated/formation-b2b-report': typeof AuthenticatedFormationB2bReportRoute
  '/_authenticated/formation-candidat': typeof AuthenticatedFormationCandidatRoute
  '/_authenticated/formation-manager': typeof AuthenticatedFormationManagerRoute
  '/_authenticated/intake': typeof AuthenticatedIntakeRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/personas': typeof AuthenticatedPersonasRoute
  '/_authenticated/pitch-setup': typeof AuthenticatedPitchSetupRoute
  '/_authenticated/profiles': typeof AuthenticatedProfilesRoute
  '/_authenticated/setup': typeof AuthenticatedSetupRoute
  '/_authenticated/simulation': typeof AuthenticatedSimulationRoute
  '/_authenticated/skills': typeof AuthenticatedSkillsRoute
  '/_authenticated/formation-b2b/labo-prix': typeof AuthenticatedFormationB2bLaboPrixRoute
  '/_authenticated/formation-b2b/setup': typeof AuthenticatedFormationB2bSetupRoute
  '/_authenticated/formation-b2b/simulation': typeof AuthenticatedFormationB2bSimulationRoute
  '/_authenticated/formation-negociation/personas': typeof AuthenticatedFormationNegociationPersonasRoute
  '/_authenticated/formation-negociation/report': typeof AuthenticatedFormationNegociationReportRoute
  '/_authenticated/formation-negociation/setup': typeof AuthenticatedFormationNegociationSetupRoute
  '/_authenticated/formation-negociation/simulation': typeof AuthenticatedFormationNegociationSimulationRoute
  '/_authenticated/play/$id': typeof AuthenticatedPlayIdRoute
  '/_authenticated/report/$id': typeof AuthenticatedReportIdRoute
  '/_authenticated/formation-b2b/': typeof AuthenticatedFormationB2bIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/formation-b2b-projection'
    | '/formation-b2b-report'
    | '/formation-candidat'
    | '/formation-manager'
    | '/intake'
    | '/onboarding'
    | '/personas'
    | '/pitch-setup'
    | '/profiles'
    | '/setup'
    | '/simulation'
    | '/skills'
    | '/formation-b2b/labo-prix'
    | '/formation-b2b/setup'
    | '/formation-b2b/simulation'
    | '/formation-negociation/personas'
    | '/formation-negociation/report'
    | '/formation-negociation/setup'
    | '/formation-negociation/simulation'
    | '/play/$id'
    | '/report/$id'
    | '/formation-b2b/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/formation-b2b-projection'
    | '/formation-b2b-report'
    | '/formation-candidat'
    | '/formation-manager'
    | '/intake'
    | '/onboarding'
    | '/personas'
    | '/pitch-setup'
    | '/profiles'
    | '/setup'
    | '/simulation'
    | '/skills'
    | '/formation-b2b/labo-prix'
    | '/formation-b2b/setup'
    | '/formation-b2b/simulation'
    | '/formation-negociation/personas'
    | '/formation-negociation/report'
    | '/formation-negociation/setup'
    | '/formation-negociation/simulation'
    | '/play/$id'
    | '/report/$id'
    | '/formation-b2b'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/formation-b2b-projection'
    | '/_authenticated/formation-b2b-report'
    | '/_authenticated/formation-candidat'
    | '/_authenticated/formation-manager'
    | '/_authenticated/intake'
    | '/_authenticated/onboarding'
    | '/_authenticated/personas'
    | '/_authenticated/pitch-setup'
    | '/_authenticated/profiles'
    | '/_authenticated/setup'
    | '/_authenticated/simulation'
    | '/_authenticated/skills'
    | '/_authenticated/formation-b2b/labo-prix'
    | '/_authenticated/formation-b2b/setup'
    | '/_authenticated/formation-b2b/simulation'
    | '/_authenticated/formation-negociation/personas'
    | '/_authenticated/formation-negociation/report'
    | '/_authenticated/formation-negociation/setup'
    | '/_authenticated/formation-negociation/simulation'
    | '/_authenticated/play/$id'
    | '/_authenticated/report/$id'
    | '/_authenticated/formation-b2b/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/skills': {
      id: '/_authenticated/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof AuthenticatedSkillsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/simulation': {
      id: '/_authenticated/simulation'
      path: '/simulation'
      fullPath: '/simulation'
      preLoaderRoute: typeof AuthenticatedSimulationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/setup': {
      id: '/_authenticated/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthenticatedSetupRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profiles': {
      id: '/_authenticated/profiles'
      path: '/profiles'
      fullPath: '/profiles'
      preLoaderRoute: typeof AuthenticatedProfilesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pitch-setup': {
      id: '/_authenticated/pitch-setup'
      path: '/pitch-setup'
      fullPath: '/pitch-setup'
      preLoaderRoute: typeof AuthenticatedPitchSetupRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/personas': {
      id: '/_authenticated/personas'
      path: '/personas'
      fullPath: '/personas'
      preLoaderRoute: typeof AuthenticatedPersonasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/intake': {
      id: '/_authenticated/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof AuthenticatedIntakeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/formation-manager': {
      id: '/_authenticated/formation-manager'
      path: '/formation-manager'
      fullPath: '/formation-manager'
      preLoaderRoute: typeof AuthenticatedFormationManagerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/formation-candidat': {
      id: '/_authenticated/formation-candidat'
      path: '/formation-candidat'
      fullPath: '/formation-candidat'
      preLoaderRoute: typeof AuthenticatedFormationCandidatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/formation-b2b-report': {
      id: '/_authenticated/formation-b2b-report'
      path: '/formation-b2b-report'
      fullPath: '/formation-b2b-report'
      preLoaderRoute: typeof AuthenticatedFormationB2bReportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/formation-b2b-projection': {
      id: '/_authenticated/formation-b2b-projection'
      path: '/formation-b2b-projection'
      fullPath: '/formation-b2b-projection'
      preLoaderRoute: typeof AuthenticatedFormationB2bProjectionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/formation-b2b/': {
      id: '/_authenticated/formation-b2b/'
      path: '/formation-b2b'
      fullPath: '/formation-b2b/'
      preLoaderRoute: typeof AuthenticatedFormationB2bIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/report/$id': {
      id: '/_authenticated/report/$id'
      path: '/report/$id'
      fullPath: '/report/$id'
      preLoaderRoute: typeof AuthenticatedReportIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/play/$id': {
      id: '/_authenticated/play/$id'
      path: '/play/$id'
      fullPath: '/play/$id'
      preLoaderRoute: typeof AuthenticatedPlayIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/formation-negociation/simulation': {
      id: '/_authenticated/formation-negociation/simulation'
      path: '/formation-negociation/simulation'
      fullPath: '/formation-negociation/simulation'
      preLoaderRoute: typeof AuthenticatedFormationNegociationSimulationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/formation-negociation/setup': {
      id: '/_authenticated/formation-negociation/setup'
      path: '/formation-negociation/setup'
      fullPath: '/formation-negociation/setup'
      preLoaderRoute: typeof AuthenticatedFormationNegociationSetupRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/formation-negociation/report': {
      id: '/_authenticated/formation-negociation/report'
      path: '/formation-negociation/report'
      fullPath: '/formation-negociation/report'
      preLoaderRoute: typeof AuthenticatedFormationNegociationReportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/formation-negociation/personas': {
      id: '/_authenticated/formation-negociation/personas'
      path: '/formation-negociation/personas'
      fullPath: '/formation-negociation/personas'
      preLoaderRoute: typeof AuthenticatedFormationNegociationPersonasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/formation-b2b/simulation': {
      id: '/_authenticated/formation-b2b/simulation'
      path: '/formation-b2b/simulation'
      fullPath: '/formation-b2b/simulation'
      preLoaderRoute: typeof AuthenticatedFormationB2bSimulationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/formation-b2b/setup': {
      id: '/_authenticated/formation-b2b/setup'
      path: '/formation-b2b/setup'
      fullPath: '/formation-b2b/setup'
      preLoaderRoute: typeof AuthenticatedFormationB2bSetupRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/formation-b2b/labo-prix': {
      id: '/_authenticated/formation-b2b/labo-prix'
      path: '/formation-b2b/labo-prix'
      fullPath: '/formation-b2b/labo-prix'
      preLoaderRoute: typeof AuthenticatedFormationB2bLaboPrixRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedFormationB2bProjectionRoute: typeof AuthenticatedFormationB2bProjectionRoute
  AuthenticatedFormationB2bReportRoute: typeof AuthenticatedFormationB2bReportRoute
  AuthenticatedFormationCandidatRoute: typeof AuthenticatedFormationCandidatRoute
  AuthenticatedFormationManagerRoute: typeof AuthenticatedFormationManagerRoute
  AuthenticatedIntakeRoute: typeof AuthenticatedIntakeRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPersonasRoute: typeof AuthenticatedPersonasRoute
  AuthenticatedPitchSetupRoute: typeof AuthenticatedPitchSetupRoute
  AuthenticatedProfilesRoute: typeof AuthenticatedProfilesRoute
  AuthenticatedSetupRoute: typeof AuthenticatedSetupRoute
  AuthenticatedSimulationRoute: typeof AuthenticatedSimulationRoute
  AuthenticatedSkillsRoute: typeof AuthenticatedSkillsRoute
  AuthenticatedFormationB2bLaboPrixRoute: typeof AuthenticatedFormationB2bLaboPrixRoute
  AuthenticatedFormationB2bSetupRoute: typeof AuthenticatedFormationB2bSetupRoute
  AuthenticatedFormationB2bSimulationRoute: typeof AuthenticatedFormationB2bSimulationRoute
  AuthenticatedFormationNegociationPersonasRoute: typeof AuthenticatedFormationNegociationPersonasRoute
  AuthenticatedFormationNegociationReportRoute: typeof AuthenticatedFormationNegociationReportRoute
  AuthenticatedFormationNegociationSetupRoute: typeof AuthenticatedFormationNegociationSetupRoute
  AuthenticatedFormationNegociationSimulationRoute: typeof AuthenticatedFormationNegociationSimulationRoute
  AuthenticatedPlayIdRoute: typeof AuthenticatedPlayIdRoute
  AuthenticatedReportIdRoute: typeof AuthenticatedReportIdRoute
  AuthenticatedFormationB2bIndexRoute: typeof AuthenticatedFormationB2bIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedFormationB2bProjectionRoute:
    AuthenticatedFormationB2bProjectionRoute,
  AuthenticatedFormationB2bReportRoute: AuthenticatedFormationB2bReportRoute,
  AuthenticatedFormationCandidatRoute: AuthenticatedFormationCandidatRoute,
  AuthenticatedFormationManagerRoute: AuthenticatedFormationManagerRoute,
  AuthenticatedIntakeRoute: AuthenticatedIntakeRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPersonasRoute: AuthenticatedPersonasRoute,
  AuthenticatedPitchSetupRoute: AuthenticatedPitchSetupRoute,
  AuthenticatedProfilesRoute: AuthenticatedProfilesRoute,
  AuthenticatedSetupRoute: AuthenticatedSetupRoute,
  AuthenticatedSimulationRoute: AuthenticatedSimulationRoute,
  AuthenticatedSkillsRoute: AuthenticatedSkillsRoute,
  AuthenticatedFormationB2bLaboPrixRoute:
    AuthenticatedFormationB2bLaboPrixRoute,
  AuthenticatedFormationB2bSetupRoute: AuthenticatedFormationB2bSetupRoute,
  AuthenticatedFormationB2bSimulationRoute:
    AuthenticatedFormationB2bSimulationRoute,
  AuthenticatedFormationNegociationPersonasRoute:
    AuthenticatedFormationNegociationPersonasRoute,
  AuthenticatedFormationNegociationReportRoute:
    AuthenticatedFormationNegociationReportRoute,
  AuthenticatedFormationNegociationSetupRoute:
    AuthenticatedFormationNegociationSetupRoute,
  AuthenticatedFormationNegociationSimulationRoute:
    AuthenticatedFormationNegociationSimulationRoute,
  AuthenticatedPlayIdRoute: AuthenticatedPlayIdRoute,
  AuthenticatedReportIdRoute: AuthenticatedReportIdRoute,
  AuthenticatedFormationB2bIndexRoute: AuthenticatedFormationB2bIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
